name: Build

on:
  push:
    branches:
      - version/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Install binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install trunk
        run: cargo binstall trunk

      - name: Build
        run: trunk build --public-url . --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: build
